name: CI

on: [push]

jobs:

  macOS:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: swift test

  Linux:
    strategy:
      matrix:
        swift_version: ['5.0', '5.1']
    runs-on: ubuntu-latest
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v1
      - run: swift test
